# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 14:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_to_execute', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', picklefield.fields.PickledObjectField(editable=False)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OwnItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', picklefield.fields.PickledObjectField(editable=False)),
                ('bought_price', picklefield.fields.PickledObjectField(editable=False)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', picklefield.fields.PickledObjectField(editable=False)),
                ('time', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', picklefield.fields.PickledObjectField(editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Price'),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Item'),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='own_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.OwnItem'),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
